name: Lighthouse CI

on:
  push:
    paths:
     - 'app/**'
     - 'i18n/**'
     - 'nuxt.config.ts'
  pull_request:
    paths:
     - 'app/**'
     - 'i18n/**'
     - 'nuxt.config.ts'

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://website.oklabflensburg.de
          uploadArtifacts: false
          temporaryPublicStorage: true
